[package]
name = "arrow-util-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.100"
console_error_panic_hook = "0.1.7"
js-sys = "0.3.76"
arrow = "55.0.0"

[lib]
crate-type = ["cdylib"]
